---
name: Build 2018.03-1

on:
  pull_request:
  push:
    paths:
      - '1/**'
      - '.github/workflows/build-1.yml'
  schedule:
    - cron: '40 3/13,21 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 1 && docker build -t amazonlinux-1 .

      - name: Run the built image.
        run: docker run --name test-1 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro amazonlinux-1

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 1/
          file: 1/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:2018.03, ${{ github.repository }}:1, ${{ github.repository }}:2018.03.0.20211201.0
