---
name: Build latest-2023

on:
  pull_request:
  push:
    paths:
      - '2023/**'
      - '.github/workflows/build-2023.yml'
  schedule:
    - cron: '20 3/13,21 * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 2023 && docker build -t amazonlinux-2023 .

      - name: Run the built image.
        run: docker run --name amazonlinux-2023 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro amazonlinux-2023

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty amazonlinux-2023 env TERM=xterm ansible --version

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 2023/
          file: 2023/Dockerfile
          platforms: linux/amd64, linux/arm64v8
          push: true
          tags: ${{ github.repository }}:latest, ${{ github.repository }}:2023, ${{ github.repository }}:2023.3.20240117.0
